#!/bin/sh

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Colorize output 
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='exa --icons'
alias lsa='exa -l --icons --no-filesize'

# xclip copy
alias copy='xclip -sel c <'

# Bookmarks
alias info='cd /home/calmius/Programming/info'
alias books='cd /home/calmius/Docs/books/progBooks/web'
alias repo='cd /home/calmius/Programming/repo'
alias dwm='cd /home/calmius/.config/dwm'
alias st='cd /home/calmius/.config/st'
alias czsh='cd /home/calmius/.config/zsh'
alias x11='cd /home/calmius/.config/X11'
    # Web
    alias web='cd /home/calmius/Programming/web'

# Soft 
alias r='ranger --choosedir=$HOME/.config/ranger/.rangerdir; LASTDIR=`cat $HOME/.config/ranger/.rangerdir`; cd "$LASTDIR"'
alias n='nvim'
#alias mc='mycli --myclirc ~/.config/mycli/myclirc'
    # Get rid of wget-hsts
    alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
    # sudo make clean install
    alias comp='sudo make clean install'
alias swap='
    # Remap caps to escape
    setxkbmap -option caps:escape
    # Swap escape and caps
    setxkbmap -option caps:swapescape
    # Toggle layouts
    setxkbmap -layout us,ru -option 'grp:lctrl_lshift_toggle'
    '
# Server
alias conn='ssh calmius@calmius.xyz'
alias ocean='ssh max@onpoz.ru'

# get fastest mirrors
alias mirror="export TMPFILE="$(mktemp)"; \
    sudo true; \
    rate-mirrors --save=$TMPFILE arch --max-delay=43200 \
      && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-backup \
      && sudo mv $TMPFILE /etc/pacman.d/mirrorlist"

# Config
alias addalias='nvim +200 ~/.config/zsh/zsh-aliases'
