#!/bin/sh

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
HISTSIZE=1000000
SAVEHIST=1000000

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export USERXSESSION="$XDG_CACHE_HOME"/X11/xsession
export ERRFILE="$XDG_CACHE_HOME"/X11/xsession-errors
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="qutebrowser"

#eval "$(fnm env)"
#export MYCLI_HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/mycli/mycli-history"
