# Remap caps to escape
setxkbmap -option caps:escape
# Swap escape and caps
setxkbmap -option caps:swapescape
# Toggle layouts
setxkbmap -layout us,ru -option 'grp:lctrl_lshift_toggle'
# Load Xresources
xrdb -load ~/.config/X11/Xresources
# Random wallpaper
~/.local/bin/randomWal 
# Compositor
picom --experimental-backends &
# Dwmblocks
dwmblocks &
# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank
# Speedy keys
xset r rate 160 40
# Hide mouse when typing
xbanish &
# Off Blue light
redshift &
# Starts puls audio
pactl stat

# dwm exec
while :; do
	ssh-agent dwm
done
while :; do
	ssh-agent dmenu
done
while :; do
	ssh-agent dwmblocks
done;

# Monitor Config
#xrandr --output eDP --primary --mode 1920x1080 --pos 1920x238 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal
# Move curser at the center
#xdotool mousemove 1000 540
